myapp/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from . import views
  
app_name = 'myapp'
  
urlpatterns = [
    path('', views.index, name='index'),
 
    # ログイン、ログアウト
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('regist', views.regist, name='regist'),
    path('regist_save', views.regist_save, name='regist_save'),
 
    # お問い合わせ
    path('contact', views.contact.as_view(), name='contact'),
    path('contact_confirm', views.contact_confirm.as_view(), name='contact_confirm'),
    path('contact_send', views.contact_send.as_view(), name='contact_send'),
 
]

pj1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace = 'myapp'))
]

myapp/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from json import JSONEncoder
from uuid import UUID
from uuid import uuid4

JSONEncoder_olddefault = JSONEncoder.default

def JSONEncoder_newdefault(self, o):
    if isinstance(o, UUID): return str(o)
    return JSONEncoder_olddefault(self, o)

JSONEncoder.default = JSONEncoder_newdefault
  
  
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""
  
    use_in_migrations = True
  
    def _create_user(self, email, password, **extra_fields):
        """Create and save a user with the given username, email, and
        password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
  
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
  
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
  
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
  
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
  
        return self._create_user(email, password, **extra_fields)
  
  
class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""
    uuid = models.UUIDField(default=uuid4,
                            primary_key=True, editable=False)
 
    email = models.EmailField(_('email address'), unique=True)
    nick_name = models.CharField(_('ニックネーム'), max_length=150, blank=True)
 
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
  
    objects = UserManager()
  
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
  
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
 
    def get_full_name(self):
        full_name = '%s' % (self.nick_name)
        return full_name.strip()
 
    def get_short_name(self):
        """Return the short name for the user."""
        return self.nick_name
 
    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
 
class LoginForm(AuthenticationForm):
 
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
 
    self.fields['username'].widget.attrs['class'] = 'form-control'
    self.fields['username'].widget.attrs['placeholder'] = 'メールアドレス'
  
    self.fields['password'].widget.attrs['class'] = 'form-control'
    self.fields['password'].widget.attrs['placeholder'] = 'パスワード'
 
 
class RegisterForm(UserCreationForm):
 
  # 入力を必須にするため、required=Trueで上書き
  email = forms.EmailField(required=True)
  nick_name = forms.CharField(required=True)
 
  class Meta:
    model = User
 
    fields = (
      "email", "password1", "password2", 
      "nick_name",
    )
 
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
 
    self.fields['nick_name'].widget.attrs['class'] = 'form-control'
    self.fields['nick_name'].widget.attrs['placeholder'] = 'お名前'
 
    self.fields['email'].widget.attrs['class'] = 'form-control'
    self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
 
    self.fields['password1'].widget.attrs['class'] = 'form-control'
    self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
  
    self.fields['password2'].widget.attrs['class'] = 'form-control'
    self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'
 
class ContactForm(forms.Form):
    name = forms.CharField(max_length=20) # 名前
    email = forms.CharField(max_length=40)
    message = forms.CharField(widget=forms.Textarea, max_length=100) #問い合わせ内容
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前'
        self.fields['name'].widget.attrs['maxlength'] = '20'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
        self.fields['name'].widget.attrs['maxlength'] = '40'
        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージ'
        self.fields['message'].widget.attrs['maxlength'] = '200'
        self.fields['message'].widget.attrs['rows'] = '6'
 
    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError("正しいメールアドレスを指定して下さい。")

class UserPasswordChangeForm(PasswordChangeForm):
    pass

myapp/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import (
  LoginForm,
  RegisterForm,
  UserPasswordChangeForm
)
from django.urls import reverse_lazy
from .forms import  ContactForm
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.contrib.auth import login as auth_login
from django.contrib.auth.backends import ModelBackend
from django.views.generic import FormView, TemplateView
from django.conf import settings
 
User = get_user_model()
 
 
def index(request):
  context = {
    'myapp':request.user,
  }
  return render(request, 'index.html', context)
 
def login(request):
    context = {
        'template_name': 'login.html',
        'authentication_form': LoginForm
    }
    return auth_views.login(request, **context)
  
  
def logout(request):
    context = {
        'template_name': 'index.html',
    }
    return auth_views.logout(request, **context)
 
 
def regist(request):
  form = RegisterForm(request.POST or None)
  context = {
    'form':form,
  }
  return render(request, 'regist.html', context)
 
@require_POST
def regist_save(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('users:index')
  
    context = {
        'form': form,
    }
    return render(request, 'regist.html', context)
 
class contact(FormView):
    """お問い合わせフォームページ"""
 
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('myapp:contact_confirm')
 
    def get_form(self, form_class=None):
        # contact.hmltで、データを送信した場合
        if 'name' in self.request.POST:
            form_data = self.request.POST
  
        # お問い合わせフォーム確認画面から「戻る」リンクを押した場合や
        # 初回の入力欄表示は以下の表示。
        # セッションにユーザーデータがあれば、それをフォームに束縛
        else:
            form_data = self.request.session.get('form_data', None)
  
        return self.form_class(form_data)
  
    def form_valid(self, form):
        # 入力した値を、セッションに保存
        self.request.session['form_data'] = self.request.POST
        return super().form_valid(form)
 
 
class contact_confirm(TemplateView):
    """お問い合わせフォーム確認ページ"""
 
    template_name = 'contact_confirm.html'
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_data = self.request.session.get('form_data', None)
        context['form'] = ContactForm(form_data)
        return context
 
 
class contact_send(FormView):
    """お問い合わせ送信"""
 
    form_class = ContactForm
    success_url = reverse_lazy('myapp:index')
  
    def get_form(self, form_class=None):
        # popで、セッションに入れたユーザーデータ自体取り出し
        form_data = self.request.session.pop('form_data', None)
 
        #メール送信
        subject = form_data['name']
        message = form_data['message']
        from_email = form_data['email']
        to = [settings.EMAIL_HOST_USER]
        send_mail(subject, message, from_email, to)
 
        return self.form_class(form_data)

myapp/templates/Base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'main/img/favicon.ico' %}">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ユーザ登録</title>
  
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
      .my-form {
        width: 640px;
        margin: 0 auto;
      }
  
      @media screen and (max-width: 768px) {
        .my-form {
          width: 100%;
        }
      }
  
      .errorlist li {
        list-style-type: none;
      }
  
      .errorlist {
        color: red;
        margin-left: 0;
        padding-left: 0;
      }
    </style>
  </head>
  
  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right"
      type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">App1</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:profile' %}"">プロフィール</a>
          </li>
        </ul>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'myapp:logout' %}">ログアウト</a>
          {% else %}
          <a class="nav-link" href="{% url 'myapp:login' %}">ログイン</a>
          {% endif %}
          </li>
        </ul>
      </div>
    </nav>
      {% block content %}
      {% endblock %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <!-- js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </body>
</html>

myapp/templates/contact.html
{% block content %}
<div class="container-fluid" style="margin-top: 30px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">お問い合わせ</div>
        <div class="card-body">
          <div class="card-block"> 
            <form class="my-form" action="" method="POST">
              <div class="row">
                <div class="form-group col-md-11">
                  <label for="id_email">お名前</label>
                  {{ form.name }}
                </div>
                <div class="form-group col-md-11 pb-0">
                  <label for="id_email">メールアドレス</label>
                  {{ form.email }}
                </div>
                <div class="form-group col-md-11" style="height: 1em;">
                  <ul class="errorlist m-0 p-0">
                  <li>
                  {% if form.email.errors %}
                      {% for error in form.email.errors %}
                          {{ error|escape }}
                      {% endfor %}
                  {% endif %}
                  </li>
                  </ul>
                </div>
                <div class="form-group col-md-11">
                  <label for="id_email">メッセージ</label>
                  {{ form.message }}
                </div>
                <div class="form-group col-md-11">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-block btn-outline-primary">送信</button>
                </div>
              </div>
            </form>
          </div>
        </div><!-- end card-body-->
      </div><!-- end card-->
    </div>
  </div><!-- end row -->
</div><!-- end container-fluid-->
{% endblock %}

myapp/templates/contact_confirm.html
{% block content %}
<div class="container-fluid" style="margin-top: 30px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">お問い合わせ内容確認</div>
        <div class="card-body">
          <div class="card-block">
            <h6 class="card-title">お名前</h6>
            <p class="card-text" style="word-wrap: break-word;">{{ form.name.value }}</p>
            <h6 class="card-title">メールアドレス</h6>
            <p class="card-text" style="word-wrap: break-word;">{{ form.email.value }}</p>
            <h6 class="card-title">メッセージ</h6>
            <p class="card-text pb-3" style="word-wrap: break-word;">{{ form.message.value }}</p>
            <form class="my-form" action="{% url 'myapp:contact_send' %}" method="POST">
              <div class="row">
                <div class="form-group col-md-11">
                  <div style="display:none">
                    {{ form }}
                    {% csrf_token %}
                  </div>
                  <button type="submit" class="btn btn-block btn-outline-primary">送信</button>
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-11">
                  <div style="display:none">
                    {{ form }}
                    {% csrf_token %}
                  </div>
                  <a href="{% url 'myapp:contact' %}" class="btn btn-block btn-outline-primary">戻る</a>
                </div>
              </div>
            </form>
          </div>
        </div><!-- end card-body-->
      </div><!-- end card-->
    </div>
  </div><!-- end row -->
</div><!-- end container-fluid-->
{% endblock %}

myapp/templates/index.html
{% block content %}
<div class="container-fluid" style="margin-top: 60px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p>インデックスです</p>
    </div><!-- end col-md-6 offset-md-3 -->
  </div><!-- end row -->
</div><!-- end container-fluid-->
{% endblock %}

myapp/templates/login.html
{% block content %}
<div class="container-fluid" style="margin-top: 60px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header"> ログイン</div>
        <div class="card-body">
          <div class="card-block"> 
            <form class="my-form" action="{% url 'myapp:login' %}" method="POST">
            {% csrf_token %}
              <div class="row">
                <div class="form-group col-md-11">
                  <label for="id_email">メールアドレス</label>
                  {{ form.username }}
                  {{ form.username.errors }}
                  <p class="help-block mb-0">{{ form.username.help_text }}</p>
                </div>
                <div class="form-group col-md-11 pb-3">
                  <label for="id_email">パスワード</label>
                  {{ form.password }}
                  {{ form.password.errors }}
                </div>
                <div class="form-group col-md-11">
                  <input type='hidden' name='next' value='{{ next }}' />
                  <button type="submit" class="btn btn-block btn-outline-primary"> ログイン</button>
                </div>
              </div>
            </form>
            <div class="card-text">
              <p class="text-right mb-0"><a class="nav-link" href="#">パスワードを忘れた方</a></p>
              <p class="text-right mb-0"><a class="nav-link" href="{% url 'users:regist' %}">新規登録会員</a></p>
            </div><!-- end card-text -->
          </div>
        </div><!-- end card-body-->
      </div><!-- end card-->
    </div>
  </div><!-- end container-fluid -->
</div><!-- end container-fluid-->
{% endblock %}

myapp/templates/regist.html
{% block content %}
<div class="container-fluid" style="margin-top: 60px;">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">会員登録用URL送信</div>
          <div class="card-body">
            <div class="card-block">
              <form class="my-form" action="" method="POST">
              {% csrf_token %}
                <div class="row">
                  <div class="form-group col-md-11">
                    <label for="id_nick_name">お名前</label>
                    {{ form.nick_name }}
                    {{ form.nick_name.errors }}
                  </div>
                  <div class="form-group col-md-11 my-0">
                    <label for="id_email">メールアドレス</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                    <p class="help-block">{{ form.email.help_text }}</p>
                  </div>
                  <div class="form-group col-md-11">
                    <label for="id_password1">パスワード</label>
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                  </div>
                  <div class="form-group col-md-11">
                    <label for="id_password2">パスワード(確認用)</label>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                    <p class="help-block">{{ form.password2.help_text }}</p>
                  </div>
                  <div class="form-group col-md-11">
                    <input type='hidden' name='next' value='{{ next }}' />
                    <button type="submit" class="btn btn-block btn-outline-primary">メールを送信する</button>
                  </div>
                </div>
              </form>
            </div><!-- end card-block -->
          </div><!-- end card-body -->
      </div><!-- end card -->
    </div><!-- end col-md-6 offset-md-3 -->
  </div><!-- end row -->
</div><!-- end container-fluid -->
{% endblock %}